// Generated by jextract

package com.ustermetrics.scip4j.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct SCIP_Interval {
 *     double inf;
 *     double sup;
 * } SCIP_INTERVAL
 * }
 */
public class SCIP_INTERVAL$127 extends SCIP_Interval {

    SCIP_INTERVAL$127() {
        // Should not be called directly
    }
}

