// Generated by jextract

package com.ustermetrics.scip4j.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class scip_h extends scip_h_1 {

    scip_h() {
        // Should not be called directly
    }
    private static final double SCIP_DEFAULT_HUGEVAL = 1.0E15d;
    /**
     * {@snippet lang=c :
     * #define SCIP_DEFAULT_HUGEVAL 1.0E15
     * }
     */
    public static double SCIP_DEFAULT_HUGEVAL() {
        return SCIP_DEFAULT_HUGEVAL;
    }
    private static final double SCIP_MAXEPSILON = 0.001d;
    /**
     * {@snippet lang=c :
     * #define SCIP_MAXEPSILON 0.001
     * }
     */
    public static double SCIP_MAXEPSILON() {
        return SCIP_MAXEPSILON;
    }
    private static final double SCIP_MINEPSILON = 1.0E-20d;
    /**
     * {@snippet lang=c :
     * #define SCIP_MINEPSILON 1.0E-20
     * }
     */
    public static double SCIP_MINEPSILON() {
        return SCIP_MINEPSILON;
    }
    private static final double SCIP_INVALID = 1.0E99d;
    /**
     * {@snippet lang=c :
     * #define SCIP_INVALID 1.0E99
     * }
     */
    public static double SCIP_INVALID() {
        return SCIP_INVALID;
    }
    private static final double SCIP_UNKNOWN = 1.0E98d;
    /**
     * {@snippet lang=c :
     * #define SCIP_UNKNOWN 1.0E98
     * }
     */
    public static double SCIP_UNKNOWN() {
        return SCIP_UNKNOWN;
    }
    private static final double SCIP_INTERVAL_INFINITY = 1.0E300d;
    /**
     * {@snippet lang=c :
     * #define SCIP_INTERVAL_INFINITY 1.0E300
     * }
     */
    public static double SCIP_INTERVAL_INFINITY() {
        return SCIP_INTERVAL_INFINITY;
    }
    /**
     * {@snippet lang=c :
     * #define SCIP_SPACECONTROL " tnvfr"
     * }
     */
    public static MemorySegment SCIP_SPACECONTROL() {
        class Holder {
            static final MemorySegment SCIP_SPACECONTROL
                = scip_h.LIBRARY_ARENA.allocateFrom(" tnvfr");
        }
        return Holder.SCIP_SPACECONTROL;
    }
    private static final long SCIP_MAXMEMSIZE = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define SCIP_MAXMEMSIZE 9223372036854775807
     * }
     */
    public static long SCIP_MAXMEMSIZE() {
        return SCIP_MAXMEMSIZE;
    }
    private static final double SCIP_DEFAULT_MEM_ARRAYGROWFAC = 1.2d;
    /**
     * {@snippet lang=c :
     * #define SCIP_DEFAULT_MEM_ARRAYGROWFAC 1.2
     * }
     */
    public static double SCIP_DEFAULT_MEM_ARRAYGROWFAC() {
        return SCIP_DEFAULT_MEM_ARRAYGROWFAC;
    }
    private static final long SCIP_MEM_NOLIMIT = 8796093022207L;
    /**
     * {@snippet lang=c :
     * #define SCIP_MEM_NOLIMIT 8796093022207
     * }
     */
    public static long SCIP_MEM_NOLIMIT() {
        return SCIP_MEM_NOLIMIT;
    }
    private static final int SCIP_PRESOLTIMING_NONE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define SCIP_PRESOLTIMING_NONE 2
     * }
     */
    public static int SCIP_PRESOLTIMING_NONE() {
        return SCIP_PRESOLTIMING_NONE;
    }
    private static final int SCIP_PRESOLTIMING_FAST = (int)4L;
    /**
     * {@snippet lang=c :
     * #define SCIP_PRESOLTIMING_FAST 4
     * }
     */
    public static int SCIP_PRESOLTIMING_FAST() {
        return SCIP_PRESOLTIMING_FAST;
    }
    private static final int SCIP_PRESOLTIMING_MEDIUM = (int)8L;
    /**
     * {@snippet lang=c :
     * #define SCIP_PRESOLTIMING_MEDIUM 8
     * }
     */
    public static int SCIP_PRESOLTIMING_MEDIUM() {
        return SCIP_PRESOLTIMING_MEDIUM;
    }
    private static final int SCIP_PRESOLTIMING_EXHAUSTIVE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define SCIP_PRESOLTIMING_EXHAUSTIVE 16
     * }
     */
    public static int SCIP_PRESOLTIMING_EXHAUSTIVE() {
        return SCIP_PRESOLTIMING_EXHAUSTIVE;
    }
    private static final int SCIP_PRESOLTIMING_FINAL = (int)32L;
    /**
     * {@snippet lang=c :
     * #define SCIP_PRESOLTIMING_FINAL 32
     * }
     */
    public static int SCIP_PRESOLTIMING_FINAL() {
        return SCIP_PRESOLTIMING_FINAL;
    }
    private static final int SCIP_PRESOLTIMING_ALWAYS = (int)28L;
    /**
     * {@snippet lang=c :
     * #define SCIP_PRESOLTIMING_ALWAYS 28
     * }
     */
    public static int SCIP_PRESOLTIMING_ALWAYS() {
        return SCIP_PRESOLTIMING_ALWAYS;
    }
    private static final int SCIP_PRESOLTIMING_MAX = (int)60L;
    /**
     * {@snippet lang=c :
     * #define SCIP_PRESOLTIMING_MAX 60
     * }
     */
    public static int SCIP_PRESOLTIMING_MAX() {
        return SCIP_PRESOLTIMING_MAX;
    }
    private static final int SCIP_PROPTIMING_BEFORELP = (int)1L;
    /**
     * {@snippet lang=c :
     * #define SCIP_PROPTIMING_BEFORELP 1
     * }
     */
    public static int SCIP_PROPTIMING_BEFORELP() {
        return SCIP_PROPTIMING_BEFORELP;
    }
    private static final int SCIP_PROPTIMING_DURINGLPLOOP = (int)2L;
    /**
     * {@snippet lang=c :
     * #define SCIP_PROPTIMING_DURINGLPLOOP 2
     * }
     */
    public static int SCIP_PROPTIMING_DURINGLPLOOP() {
        return SCIP_PROPTIMING_DURINGLPLOOP;
    }
    private static final int SCIP_PROPTIMING_AFTERLPLOOP = (int)4L;
    /**
     * {@snippet lang=c :
     * #define SCIP_PROPTIMING_AFTERLPLOOP 4
     * }
     */
    public static int SCIP_PROPTIMING_AFTERLPLOOP() {
        return SCIP_PROPTIMING_AFTERLPLOOP;
    }
    private static final int SCIP_PROPTIMING_AFTERLPNODE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define SCIP_PROPTIMING_AFTERLPNODE 8
     * }
     */
    public static int SCIP_PROPTIMING_AFTERLPNODE() {
        return SCIP_PROPTIMING_AFTERLPNODE;
    }
    private static final int SCIP_PROPTIMING_ALWAYS = (int)15L;
    /**
     * {@snippet lang=c :
     * #define SCIP_PROPTIMING_ALWAYS 15
     * }
     */
    public static int SCIP_PROPTIMING_ALWAYS() {
        return SCIP_PROPTIMING_ALWAYS;
    }
    private static final int SCIP_HEURTIMING_BEFORENODE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURTIMING_BEFORENODE 1
     * }
     */
    public static int SCIP_HEURTIMING_BEFORENODE() {
        return SCIP_HEURTIMING_BEFORENODE;
    }
    private static final int SCIP_HEURTIMING_DURINGLPLOOP = (int)2L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURTIMING_DURINGLPLOOP 2
     * }
     */
    public static int SCIP_HEURTIMING_DURINGLPLOOP() {
        return SCIP_HEURTIMING_DURINGLPLOOP;
    }
    private static final int SCIP_HEURTIMING_AFTERLPLOOP = (int)4L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURTIMING_AFTERLPLOOP 4
     * }
     */
    public static int SCIP_HEURTIMING_AFTERLPLOOP() {
        return SCIP_HEURTIMING_AFTERLPLOOP;
    }
    private static final int SCIP_HEURTIMING_AFTERLPNODE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURTIMING_AFTERLPNODE 8
     * }
     */
    public static int SCIP_HEURTIMING_AFTERLPNODE() {
        return SCIP_HEURTIMING_AFTERLPNODE;
    }
    private static final int SCIP_HEURTIMING_AFTERPSEUDONODE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURTIMING_AFTERPSEUDONODE 16
     * }
     */
    public static int SCIP_HEURTIMING_AFTERPSEUDONODE() {
        return SCIP_HEURTIMING_AFTERPSEUDONODE;
    }
    private static final int SCIP_HEURTIMING_AFTERLPPLUNGE = (int)32L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURTIMING_AFTERLPPLUNGE 32
     * }
     */
    public static int SCIP_HEURTIMING_AFTERLPPLUNGE() {
        return SCIP_HEURTIMING_AFTERLPPLUNGE;
    }
    private static final int SCIP_HEURTIMING_AFTERPSEUDOPLUNGE = (int)64L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURTIMING_AFTERPSEUDOPLUNGE 64
     * }
     */
    public static int SCIP_HEURTIMING_AFTERPSEUDOPLUNGE() {
        return SCIP_HEURTIMING_AFTERPSEUDOPLUNGE;
    }
    private static final int SCIP_HEURTIMING_DURINGPRICINGLOOP = (int)128L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURTIMING_DURINGPRICINGLOOP 128
     * }
     */
    public static int SCIP_HEURTIMING_DURINGPRICINGLOOP() {
        return SCIP_HEURTIMING_DURINGPRICINGLOOP;
    }
    private static final int SCIP_HEURTIMING_BEFOREPRESOL = (int)256L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURTIMING_BEFOREPRESOL 256
     * }
     */
    public static int SCIP_HEURTIMING_BEFOREPRESOL() {
        return SCIP_HEURTIMING_BEFOREPRESOL;
    }
    private static final int SCIP_HEURTIMING_DURINGPRESOLLOOP = (int)512L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURTIMING_DURINGPRESOLLOOP 512
     * }
     */
    public static int SCIP_HEURTIMING_DURINGPRESOLLOOP() {
        return SCIP_HEURTIMING_DURINGPRESOLLOOP;
    }
    private static final int SCIP_HEURTIMING_AFTERPROPLOOP = (int)1024L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURTIMING_AFTERPROPLOOP 1024
     * }
     */
    public static int SCIP_HEURTIMING_AFTERPROPLOOP() {
        return SCIP_HEURTIMING_AFTERPROPLOOP;
    }
    private static final int SCIP_HEURTIMING_AFTERNODE = (int)24L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURTIMING_AFTERNODE 24
     * }
     */
    public static int SCIP_HEURTIMING_AFTERNODE() {
        return SCIP_HEURTIMING_AFTERNODE;
    }
    private static final int SCIP_HEURTIMING_AFTERPLUNGE = (int)96L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURTIMING_AFTERPLUNGE 96
     * }
     */
    public static int SCIP_HEURTIMING_AFTERPLUNGE() {
        return SCIP_HEURTIMING_AFTERPLUNGE;
    }
    private static final long SCIP_EVENTTYPE_DISABLED = 0L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_DISABLED 0
     * }
     */
    public static long SCIP_EVENTTYPE_DISABLED() {
        return SCIP_EVENTTYPE_DISABLED;
    }
    private static final long SCIP_EVENTTYPE_VARADDED = 1L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_VARADDED 1
     * }
     */
    public static long SCIP_EVENTTYPE_VARADDED() {
        return SCIP_EVENTTYPE_VARADDED;
    }
    private static final long SCIP_EVENTTYPE_VARDELETED = 2L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_VARDELETED 2
     * }
     */
    public static long SCIP_EVENTTYPE_VARDELETED() {
        return SCIP_EVENTTYPE_VARDELETED;
    }
    private static final long SCIP_EVENTTYPE_VARFIXED = 4L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_VARFIXED 4
     * }
     */
    public static long SCIP_EVENTTYPE_VARFIXED() {
        return SCIP_EVENTTYPE_VARFIXED;
    }
    private static final long SCIP_EVENTTYPE_VARUNLOCKED = 8L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_VARUNLOCKED 8
     * }
     */
    public static long SCIP_EVENTTYPE_VARUNLOCKED() {
        return SCIP_EVENTTYPE_VARUNLOCKED;
    }
    private static final long SCIP_EVENTTYPE_OBJCHANGED = 16L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_OBJCHANGED 16
     * }
     */
    public static long SCIP_EVENTTYPE_OBJCHANGED() {
        return SCIP_EVENTTYPE_OBJCHANGED;
    }
    private static final long SCIP_EVENTTYPE_GLBCHANGED = 32L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_GLBCHANGED 32
     * }
     */
    public static long SCIP_EVENTTYPE_GLBCHANGED() {
        return SCIP_EVENTTYPE_GLBCHANGED;
    }
    private static final long SCIP_EVENTTYPE_GUBCHANGED = 64L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_GUBCHANGED 64
     * }
     */
    public static long SCIP_EVENTTYPE_GUBCHANGED() {
        return SCIP_EVENTTYPE_GUBCHANGED;
    }
    private static final long SCIP_EVENTTYPE_LBTIGHTENED = 128L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_LBTIGHTENED 128
     * }
     */
    public static long SCIP_EVENTTYPE_LBTIGHTENED() {
        return SCIP_EVENTTYPE_LBTIGHTENED;
    }
    private static final long SCIP_EVENTTYPE_LBRELAXED = 256L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_LBRELAXED 256
     * }
     */
    public static long SCIP_EVENTTYPE_LBRELAXED() {
        return SCIP_EVENTTYPE_LBRELAXED;
    }
    private static final long SCIP_EVENTTYPE_UBTIGHTENED = 512L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_UBTIGHTENED 512
     * }
     */
    public static long SCIP_EVENTTYPE_UBTIGHTENED() {
        return SCIP_EVENTTYPE_UBTIGHTENED;
    }
    private static final long SCIP_EVENTTYPE_UBRELAXED = 1024L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_UBRELAXED 1024
     * }
     */
    public static long SCIP_EVENTTYPE_UBRELAXED() {
        return SCIP_EVENTTYPE_UBRELAXED;
    }
    private static final long SCIP_EVENTTYPE_GHOLEADDED = 2048L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_GHOLEADDED 2048
     * }
     */
    public static long SCIP_EVENTTYPE_GHOLEADDED() {
        return SCIP_EVENTTYPE_GHOLEADDED;
    }
    private static final long SCIP_EVENTTYPE_GHOLEREMOVED = 4096L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_GHOLEREMOVED 4096
     * }
     */
    public static long SCIP_EVENTTYPE_GHOLEREMOVED() {
        return SCIP_EVENTTYPE_GHOLEREMOVED;
    }
    private static final long SCIP_EVENTTYPE_LHOLEADDED = 8192L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_LHOLEADDED 8192
     * }
     */
    public static long SCIP_EVENTTYPE_LHOLEADDED() {
        return SCIP_EVENTTYPE_LHOLEADDED;
    }
    private static final long SCIP_EVENTTYPE_LHOLEREMOVED = 16384L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_LHOLEREMOVED 16384
     * }
     */
    public static long SCIP_EVENTTYPE_LHOLEREMOVED() {
        return SCIP_EVENTTYPE_LHOLEREMOVED;
    }
    private static final long SCIP_EVENTTYPE_IMPLADDED = 32768L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_IMPLADDED 32768
     * }
     */
    public static long SCIP_EVENTTYPE_IMPLADDED() {
        return SCIP_EVENTTYPE_IMPLADDED;
    }
    private static final long SCIP_EVENTTYPE_TYPECHANGED = 65536L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_TYPECHANGED 65536
     * }
     */
    public static long SCIP_EVENTTYPE_TYPECHANGED() {
        return SCIP_EVENTTYPE_TYPECHANGED;
    }
    private static final long SCIP_EVENTTYPE_PRESOLVEROUND = 131072L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_PRESOLVEROUND 131072
     * }
     */
    public static long SCIP_EVENTTYPE_PRESOLVEROUND() {
        return SCIP_EVENTTYPE_PRESOLVEROUND;
    }
    private static final long SCIP_EVENTTYPE_NODEFOCUSED = 262144L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_NODEFOCUSED 262144
     * }
     */
    public static long SCIP_EVENTTYPE_NODEFOCUSED() {
        return SCIP_EVENTTYPE_NODEFOCUSED;
    }
    private static final long SCIP_EVENTTYPE_NODEFEASIBLE = 524288L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_NODEFEASIBLE 524288
     * }
     */
    public static long SCIP_EVENTTYPE_NODEFEASIBLE() {
        return SCIP_EVENTTYPE_NODEFEASIBLE;
    }
    private static final long SCIP_EVENTTYPE_NODEINFEASIBLE = 1048576L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_NODEINFEASIBLE 1048576
     * }
     */
    public static long SCIP_EVENTTYPE_NODEINFEASIBLE() {
        return SCIP_EVENTTYPE_NODEINFEASIBLE;
    }
    private static final long SCIP_EVENTTYPE_NODEBRANCHED = 2097152L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_NODEBRANCHED 2097152
     * }
     */
    public static long SCIP_EVENTTYPE_NODEBRANCHED() {
        return SCIP_EVENTTYPE_NODEBRANCHED;
    }
    private static final long SCIP_EVENTTYPE_NODEDELETE = 4194304L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_NODEDELETE 4194304
     * }
     */
    public static long SCIP_EVENTTYPE_NODEDELETE() {
        return SCIP_EVENTTYPE_NODEDELETE;
    }
    private static final long SCIP_EVENTTYPE_FIRSTLPSOLVED = 8388608L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_FIRSTLPSOLVED 8388608
     * }
     */
    public static long SCIP_EVENTTYPE_FIRSTLPSOLVED() {
        return SCIP_EVENTTYPE_FIRSTLPSOLVED;
    }
    private static final long SCIP_EVENTTYPE_LPSOLVED = 16777216L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_LPSOLVED 16777216
     * }
     */
    public static long SCIP_EVENTTYPE_LPSOLVED() {
        return SCIP_EVENTTYPE_LPSOLVED;
    }
    private static final long SCIP_EVENTTYPE_POORSOLFOUND = 33554432L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_POORSOLFOUND 33554432
     * }
     */
    public static long SCIP_EVENTTYPE_POORSOLFOUND() {
        return SCIP_EVENTTYPE_POORSOLFOUND;
    }
    private static final long SCIP_EVENTTYPE_BESTSOLFOUND = 67108864L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_BESTSOLFOUND 67108864
     * }
     */
    public static long SCIP_EVENTTYPE_BESTSOLFOUND() {
        return SCIP_EVENTTYPE_BESTSOLFOUND;
    }
    private static final long SCIP_EVENTTYPE_ROWADDEDSEPA = 134217728L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_ROWADDEDSEPA 134217728
     * }
     */
    public static long SCIP_EVENTTYPE_ROWADDEDSEPA() {
        return SCIP_EVENTTYPE_ROWADDEDSEPA;
    }
    private static final long SCIP_EVENTTYPE_ROWDELETEDSEPA = 268435456L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_ROWDELETEDSEPA 268435456
     * }
     */
    public static long SCIP_EVENTTYPE_ROWDELETEDSEPA() {
        return SCIP_EVENTTYPE_ROWDELETEDSEPA;
    }
    private static final long SCIP_EVENTTYPE_ROWADDEDLP = 536870912L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_ROWADDEDLP 536870912
     * }
     */
    public static long SCIP_EVENTTYPE_ROWADDEDLP() {
        return SCIP_EVENTTYPE_ROWADDEDLP;
    }
    private static final long SCIP_EVENTTYPE_ROWDELETEDLP = 1073741824L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_ROWDELETEDLP 1073741824
     * }
     */
    public static long SCIP_EVENTTYPE_ROWDELETEDLP() {
        return SCIP_EVENTTYPE_ROWDELETEDLP;
    }
    private static final long SCIP_EVENTTYPE_ROWCOEFCHANGED = 2147483648L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_ROWCOEFCHANGED 2147483648
     * }
     */
    public static long SCIP_EVENTTYPE_ROWCOEFCHANGED() {
        return SCIP_EVENTTYPE_ROWCOEFCHANGED;
    }
    private static final long SCIP_EVENTTYPE_ROWCONSTCHANGED = 4294967296L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_ROWCONSTCHANGED 4294967296
     * }
     */
    public static long SCIP_EVENTTYPE_ROWCONSTCHANGED() {
        return SCIP_EVENTTYPE_ROWCONSTCHANGED;
    }
    private static final long SCIP_EVENTTYPE_ROWSIDECHANGED = 8589934592L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_ROWSIDECHANGED 8589934592
     * }
     */
    public static long SCIP_EVENTTYPE_ROWSIDECHANGED() {
        return SCIP_EVENTTYPE_ROWSIDECHANGED;
    }
    private static final long SCIP_EVENTTYPE_SYNC = 17179869184L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_SYNC 17179869184
     * }
     */
    public static long SCIP_EVENTTYPE_SYNC() {
        return SCIP_EVENTTYPE_SYNC;
    }
    private static final long SCIP_EVENTTYPE_GBDCHANGED = 96L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_GBDCHANGED 96
     * }
     */
    public static long SCIP_EVENTTYPE_GBDCHANGED() {
        return SCIP_EVENTTYPE_GBDCHANGED;
    }
    private static final long SCIP_EVENTTYPE_LBCHANGED = 384L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_LBCHANGED 384
     * }
     */
    public static long SCIP_EVENTTYPE_LBCHANGED() {
        return SCIP_EVENTTYPE_LBCHANGED;
    }
    private static final long SCIP_EVENTTYPE_UBCHANGED = 1536L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_UBCHANGED 1536
     * }
     */
    public static long SCIP_EVENTTYPE_UBCHANGED() {
        return SCIP_EVENTTYPE_UBCHANGED;
    }
    private static final long SCIP_EVENTTYPE_BOUNDTIGHTENED = 640L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_BOUNDTIGHTENED 640
     * }
     */
    public static long SCIP_EVENTTYPE_BOUNDTIGHTENED() {
        return SCIP_EVENTTYPE_BOUNDTIGHTENED;
    }
    private static final long SCIP_EVENTTYPE_BOUNDRELAXED = 1280L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_BOUNDRELAXED 1280
     * }
     */
    public static long SCIP_EVENTTYPE_BOUNDRELAXED() {
        return SCIP_EVENTTYPE_BOUNDRELAXED;
    }
    private static final long SCIP_EVENTTYPE_BOUNDCHANGED = 1920L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_BOUNDCHANGED 1920
     * }
     */
    public static long SCIP_EVENTTYPE_BOUNDCHANGED() {
        return SCIP_EVENTTYPE_BOUNDCHANGED;
    }
    private static final long SCIP_EVENTTYPE_GHOLECHANGED = 6144L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_GHOLECHANGED 6144
     * }
     */
    public static long SCIP_EVENTTYPE_GHOLECHANGED() {
        return SCIP_EVENTTYPE_GHOLECHANGED;
    }
    private static final long SCIP_EVENTTYPE_LHOLECHANGED = 24576L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_LHOLECHANGED 24576
     * }
     */
    public static long SCIP_EVENTTYPE_LHOLECHANGED() {
        return SCIP_EVENTTYPE_LHOLECHANGED;
    }
    private static final long SCIP_EVENTTYPE_HOLECHANGED = 30720L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_HOLECHANGED 30720
     * }
     */
    public static long SCIP_EVENTTYPE_HOLECHANGED() {
        return SCIP_EVENTTYPE_HOLECHANGED;
    }
    private static final long SCIP_EVENTTYPE_DOMCHANGED = 32640L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_DOMCHANGED 32640
     * }
     */
    public static long SCIP_EVENTTYPE_DOMCHANGED() {
        return SCIP_EVENTTYPE_DOMCHANGED;
    }
    private static final long SCIP_EVENTTYPE_VARCHANGED = 131070L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_VARCHANGED 131070
     * }
     */
    public static long SCIP_EVENTTYPE_VARCHANGED() {
        return SCIP_EVENTTYPE_VARCHANGED;
    }
    private static final long SCIP_EVENTTYPE_VAREVENT = 131071L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_VAREVENT 131071
     * }
     */
    public static long SCIP_EVENTTYPE_VAREVENT() {
        return SCIP_EVENTTYPE_VAREVENT;
    }
    private static final long SCIP_EVENTTYPE_NODESOLVED = 3670016L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_NODESOLVED 3670016
     * }
     */
    public static long SCIP_EVENTTYPE_NODESOLVED() {
        return SCIP_EVENTTYPE_NODESOLVED;
    }
    private static final long SCIP_EVENTTYPE_NODEEVENT = 3932160L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_NODEEVENT 3932160
     * }
     */
    public static long SCIP_EVENTTYPE_NODEEVENT() {
        return SCIP_EVENTTYPE_NODEEVENT;
    }
    private static final long SCIP_EVENTTYPE_LPEVENT = 25165824L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_LPEVENT 25165824
     * }
     */
    public static long SCIP_EVENTTYPE_LPEVENT() {
        return SCIP_EVENTTYPE_LPEVENT;
    }
    private static final long SCIP_EVENTTYPE_SOLFOUND = 100663296L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_SOLFOUND 100663296
     * }
     */
    public static long SCIP_EVENTTYPE_SOLFOUND() {
        return SCIP_EVENTTYPE_SOLFOUND;
    }
    private static final long SCIP_EVENTTYPE_SOLEVENT = 100663296L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_SOLEVENT 100663296
     * }
     */
    public static long SCIP_EVENTTYPE_SOLEVENT() {
        return SCIP_EVENTTYPE_SOLEVENT;
    }
    private static final long SCIP_EVENTTYPE_ROWCHANGED = 15032385536L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_ROWCHANGED 15032385536
     * }
     */
    public static long SCIP_EVENTTYPE_ROWCHANGED() {
        return SCIP_EVENTTYPE_ROWCHANGED;
    }
    private static final long SCIP_EVENTTYPE_ROWEVENT = 17045651456L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_ROWEVENT 17045651456
     * }
     */
    public static long SCIP_EVENTTYPE_ROWEVENT() {
        return SCIP_EVENTTYPE_ROWEVENT;
    }
    /**
     * {@snippet lang=c :
     * #define SCIP_EVENTTYPE_FORMAT "lx"
     * }
     */
    public static MemorySegment SCIP_EVENTTYPE_FORMAT() {
        class Holder {
            static final MemorySegment SCIP_EVENTTYPE_FORMAT
                = scip_h.LIBRARY_ARENA.allocateFrom("lx");
        }
        return Holder.SCIP_EVENTTYPE_FORMAT;
    }
    private static final int SCIP_DIVETYPE_NONE = (int)0L;
    /**
     * {@snippet lang=c :
     * #define SCIP_DIVETYPE_NONE 0
     * }
     */
    public static int SCIP_DIVETYPE_NONE() {
        return SCIP_DIVETYPE_NONE;
    }
    private static final int SCIP_DIVETYPE_INTEGRALITY = (int)1L;
    /**
     * {@snippet lang=c :
     * #define SCIP_DIVETYPE_INTEGRALITY 1
     * }
     */
    public static int SCIP_DIVETYPE_INTEGRALITY() {
        return SCIP_DIVETYPE_INTEGRALITY;
    }
    private static final int SCIP_DIVETYPE_SOS1VARIABLE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define SCIP_DIVETYPE_SOS1VARIABLE 2
     * }
     */
    public static int SCIP_DIVETYPE_SOS1VARIABLE() {
        return SCIP_DIVETYPE_SOS1VARIABLE;
    }
    private static final int SCIP_HEURDISPCHAR_LNS = (int)76L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURDISPCHAR_LNS 76
     * }
     */
    public static int SCIP_HEURDISPCHAR_LNS() {
        return SCIP_HEURDISPCHAR_LNS;
    }
    private static final int SCIP_HEURDISPCHAR_DIVING = (int)100L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURDISPCHAR_DIVING 100
     * }
     */
    public static int SCIP_HEURDISPCHAR_DIVING() {
        return SCIP_HEURDISPCHAR_DIVING;
    }
    private static final int SCIP_HEURDISPCHAR_ITERATIVE = (int)105L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURDISPCHAR_ITERATIVE 105
     * }
     */
    public static int SCIP_HEURDISPCHAR_ITERATIVE() {
        return SCIP_HEURDISPCHAR_ITERATIVE;
    }
    private static final int SCIP_HEURDISPCHAR_OBJDIVING = (int)111L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURDISPCHAR_OBJDIVING 111
     * }
     */
    public static int SCIP_HEURDISPCHAR_OBJDIVING() {
        return SCIP_HEURDISPCHAR_OBJDIVING;
    }
    private static final int SCIP_HEURDISPCHAR_PROP = (int)112L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURDISPCHAR_PROP 112
     * }
     */
    public static int SCIP_HEURDISPCHAR_PROP() {
        return SCIP_HEURDISPCHAR_PROP;
    }
    private static final int SCIP_HEURDISPCHAR_ROUNDING = (int)114L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURDISPCHAR_ROUNDING 114
     * }
     */
    public static int SCIP_HEURDISPCHAR_ROUNDING() {
        return SCIP_HEURDISPCHAR_ROUNDING;
    }
    private static final int SCIP_HEURDISPCHAR_TRIVIAL = (int)116L;
    /**
     * {@snippet lang=c :
     * #define SCIP_HEURDISPCHAR_TRIVIAL 116
     * }
     */
    public static int SCIP_HEURDISPCHAR_TRIVIAL() {
        return SCIP_HEURDISPCHAR_TRIVIAL;
    }
    private static final int SCIP_NLINCONSTYPES = (int)17L;
    /**
     * {@snippet lang=c :
     * #define SCIP_NLINCONSTYPES 17
     * }
     */
    public static int SCIP_NLINCONSTYPES() {
        return SCIP_NLINCONSTYPES;
    }
    private static final int SCIP_EXPRITER_ENTEREXPR = (int)1L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EXPRITER_ENTEREXPR 1
     * }
     */
    public static int SCIP_EXPRITER_ENTEREXPR() {
        return SCIP_EXPRITER_ENTEREXPR;
    }
    private static final int SCIP_EXPRITER_VISITINGCHILD = (int)2L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EXPRITER_VISITINGCHILD 2
     * }
     */
    public static int SCIP_EXPRITER_VISITINGCHILD() {
        return SCIP_EXPRITER_VISITINGCHILD;
    }
    private static final int SCIP_EXPRITER_VISITEDCHILD = (int)4L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EXPRITER_VISITEDCHILD 4
     * }
     */
    public static int SCIP_EXPRITER_VISITEDCHILD() {
        return SCIP_EXPRITER_VISITEDCHILD;
    }
    private static final int SCIP_EXPRITER_LEAVEEXPR = (int)8L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EXPRITER_LEAVEEXPR 8
     * }
     */
    public static int SCIP_EXPRITER_LEAVEEXPR() {
        return SCIP_EXPRITER_LEAVEEXPR;
    }
    private static final int SCIP_EXPRITER_ALLSTAGES = (int)15L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EXPRITER_ALLSTAGES 15
     * }
     */
    public static int SCIP_EXPRITER_ALLSTAGES() {
        return SCIP_EXPRITER_ALLSTAGES;
    }
    private static final int SCIP_EXPRPRINT_EXPRSTRING = (int)1L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EXPRPRINT_EXPRSTRING 1
     * }
     */
    public static int SCIP_EXPRPRINT_EXPRSTRING() {
        return SCIP_EXPRPRINT_EXPRSTRING;
    }
    private static final int SCIP_EXPRPRINT_EXPRHDLR = (int)2L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EXPRPRINT_EXPRHDLR 2
     * }
     */
    public static int SCIP_EXPRPRINT_EXPRHDLR() {
        return SCIP_EXPRPRINT_EXPRHDLR;
    }
    private static final int SCIP_EXPRPRINT_NUSES = (int)4L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EXPRPRINT_NUSES 4
     * }
     */
    public static int SCIP_EXPRPRINT_NUSES() {
        return SCIP_EXPRPRINT_NUSES;
    }
    private static final int SCIP_EXPRPRINT_EVALVALUE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EXPRPRINT_EVALVALUE 8
     * }
     */
    public static int SCIP_EXPRPRINT_EVALVALUE() {
        return SCIP_EXPRPRINT_EVALVALUE;
    }
    private static final int SCIP_EXPRPRINT_EVALTAG = (int)24L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EXPRPRINT_EVALTAG 24
     * }
     */
    public static int SCIP_EXPRPRINT_EVALTAG() {
        return SCIP_EXPRPRINT_EVALTAG;
    }
    private static final int SCIP_EXPRPRINT_ACTIVITY = (int)32L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EXPRPRINT_ACTIVITY 32
     * }
     */
    public static int SCIP_EXPRPRINT_ACTIVITY() {
        return SCIP_EXPRPRINT_ACTIVITY;
    }
    private static final int SCIP_EXPRPRINT_ACTIVITYTAG = (int)96L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EXPRPRINT_ACTIVITYTAG 96
     * }
     */
    public static int SCIP_EXPRPRINT_ACTIVITYTAG() {
        return SCIP_EXPRPRINT_ACTIVITYTAG;
    }
    private static final int SCIP_EXPRPRINT_OWNER = (int)128L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EXPRPRINT_OWNER 128
     * }
     */
    public static int SCIP_EXPRPRINT_OWNER() {
        return SCIP_EXPRPRINT_OWNER;
    }
    private static final int SCIP_EXPRPRINT_ALL = (int)255L;
    /**
     * {@snippet lang=c :
     * #define SCIP_EXPRPRINT_ALL 255
     * }
     */
    public static int SCIP_EXPRPRINT_ALL() {
        return SCIP_EXPRPRINT_ALL;
    }
    private static final int SCIP_DECOMP_LINKVAR = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define SCIP_DECOMP_LINKVAR -1
     * }
     */
    public static int SCIP_DECOMP_LINKVAR() {
        return SCIP_DECOMP_LINKVAR;
    }
    private static final int SCIP_DECOMP_LINKCONS = (int)-2L;
    /**
     * {@snippet lang=c :
     * #define SCIP_DECOMP_LINKCONS -2
     * }
     */
    public static int SCIP_DECOMP_LINKCONS() {
        return SCIP_DECOMP_LINKCONS;
    }
    private static final double QUAD_EPSILON = 1.0E-12d;
    /**
     * {@snippet lang=c :
     * #define QUAD_EPSILON 1.0E-12
     * }
     */
    public static double QUAD_EPSILON() {
        return QUAD_EPSILON;
    }
    private static final int SCIP_NLHDLR_METHOD_NONE = (int)0L;
    /**
     * {@snippet lang=c :
     * #define SCIP_NLHDLR_METHOD_NONE 0
     * }
     */
    public static int SCIP_NLHDLR_METHOD_NONE() {
        return SCIP_NLHDLR_METHOD_NONE;
    }
    private static final int SCIP_NLHDLR_METHOD_SEPABELOW = (int)1L;
    /**
     * {@snippet lang=c :
     * #define SCIP_NLHDLR_METHOD_SEPABELOW 1
     * }
     */
    public static int SCIP_NLHDLR_METHOD_SEPABELOW() {
        return SCIP_NLHDLR_METHOD_SEPABELOW;
    }
    private static final int SCIP_NLHDLR_METHOD_SEPAABOVE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define SCIP_NLHDLR_METHOD_SEPAABOVE 2
     * }
     */
    public static int SCIP_NLHDLR_METHOD_SEPAABOVE() {
        return SCIP_NLHDLR_METHOD_SEPAABOVE;
    }
    private static final int SCIP_NLHDLR_METHOD_SEPABOTH = (int)3L;
    /**
     * {@snippet lang=c :
     * #define SCIP_NLHDLR_METHOD_SEPABOTH 3
     * }
     */
    public static int SCIP_NLHDLR_METHOD_SEPABOTH() {
        return SCIP_NLHDLR_METHOD_SEPABOTH;
    }
    private static final int SCIP_NLHDLR_METHOD_ACTIVITY = (int)4L;
    /**
     * {@snippet lang=c :
     * #define SCIP_NLHDLR_METHOD_ACTIVITY 4
     * }
     */
    public static int SCIP_NLHDLR_METHOD_ACTIVITY() {
        return SCIP_NLHDLR_METHOD_ACTIVITY;
    }
    private static final int SCIP_NLHDLR_METHOD_ALL = (int)7L;
    /**
     * {@snippet lang=c :
     * #define SCIP_NLHDLR_METHOD_ALL 7
     * }
     */
    public static int SCIP_NLHDLR_METHOD_ALL() {
        return SCIP_NLHDLR_METHOD_ALL;
    }
    private static final int SYM_SPEC_INTEGER = (int)1L;
    /**
     * {@snippet lang=c :
     * #define SYM_SPEC_INTEGER 1
     * }
     */
    public static int SYM_SPEC_INTEGER() {
        return SYM_SPEC_INTEGER;
    }
    private static final int SYM_SPEC_BINARY = (int)2L;
    /**
     * {@snippet lang=c :
     * #define SYM_SPEC_BINARY 2
     * }
     */
    public static int SYM_SPEC_BINARY() {
        return SYM_SPEC_BINARY;
    }
    private static final int SYM_SPEC_REAL = (int)4L;
    /**
     * {@snippet lang=c :
     * #define SYM_SPEC_REAL 4
     * }
     */
    public static int SYM_SPEC_REAL() {
        return SYM_SPEC_REAL;
    }
    private static final int SYM_COMPUTETIMING_BEFOREPRESOL = (int)0L;
    /**
     * {@snippet lang=c :
     * #define SYM_COMPUTETIMING_BEFOREPRESOL 0
     * }
     */
    public static int SYM_COMPUTETIMING_BEFOREPRESOL() {
        return SYM_COMPUTETIMING_BEFOREPRESOL;
    }
    private static final int SYM_COMPUTETIMING_DURINGPRESOL = (int)1L;
    /**
     * {@snippet lang=c :
     * #define SYM_COMPUTETIMING_DURINGPRESOL 1
     * }
     */
    public static int SYM_COMPUTETIMING_DURINGPRESOL() {
        return SYM_COMPUTETIMING_DURINGPRESOL;
    }
    private static final int SYM_COMPUTETIMING_AFTERPRESOL = (int)2L;
    /**
     * {@snippet lang=c :
     * #define SYM_COMPUTETIMING_AFTERPRESOL 2
     * }
     */
    public static int SYM_COMPUTETIMING_AFTERPRESOL() {
        return SYM_COMPUTETIMING_AFTERPRESOL;
    }
    private static final int SYM_HANDLETYPE_NONE = (int)0L;
    /**
     * {@snippet lang=c :
     * #define SYM_HANDLETYPE_NONE 0
     * }
     */
    public static int SYM_HANDLETYPE_NONE() {
        return SYM_HANDLETYPE_NONE;
    }
    private static final int SYM_HANDLETYPE_SYMBREAK = (int)1L;
    /**
     * {@snippet lang=c :
     * #define SYM_HANDLETYPE_SYMBREAK 1
     * }
     */
    public static int SYM_HANDLETYPE_SYMBREAK() {
        return SYM_HANDLETYPE_SYMBREAK;
    }
    private static final int SYM_HANDLETYPE_ORBITALREDUCTION = (int)2L;
    /**
     * {@snippet lang=c :
     * #define SYM_HANDLETYPE_ORBITALREDUCTION 2
     * }
     */
    public static int SYM_HANDLETYPE_ORBITALREDUCTION() {
        return SYM_HANDLETYPE_ORBITALREDUCTION;
    }
    private static final int SYM_HANDLETYPE_SST = (int)4L;
    /**
     * {@snippet lang=c :
     * #define SYM_HANDLETYPE_SST 4
     * }
     */
    public static int SYM_HANDLETYPE_SST() {
        return SYM_HANDLETYPE_SST;
    }
    private static final int SYM_HANDLETYPE_SYMCONS = (int)5L;
    /**
     * {@snippet lang=c :
     * #define SYM_HANDLETYPE_SYMCONS 5
     * }
     */
    public static int SYM_HANDLETYPE_SYMCONS() {
        return SYM_HANDLETYPE_SYMCONS;
    }
    /**
     * {@snippet lang=c :
     * #define ARTIFICIALVARNAMEPREFIX "andresultant_"
     * }
     */
    public static MemorySegment ARTIFICIALVARNAMEPREFIX() {
        class Holder {
            static final MemorySegment ARTIFICIALVARNAMEPREFIX
                = scip_h.LIBRARY_ARENA.allocateFrom("andresultant_");
        }
        return Holder.ARTIFICIALVARNAMEPREFIX;
    }
}

