// Generated by jextract

package com.ustermetrics.scip4j.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct SCIP_ConsNonlinear_Auxexpr {
 *     double coefs[3];
 *     double cst;
 *     SCIP_VAR *auxvar;
 *     unsigned int underestimate;
 *     unsigned int overestimate;
 * } SCIP_CONSNONLINEAR_AUXEXPR
 * }
 */
public class SCIP_CONSNONLINEAR_AUXEXPR$207 extends SCIP_ConsNonlinear_Auxexpr {

    SCIP_CONSNONLINEAR_AUXEXPR$207() {
        // Should not be called directly
    }
}

