// Generated by jextract

package com.ustermetrics.scip4j.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct SCIP_ConsNonlinear_BilinTerm {
 *     SCIP_VAR *x;
 *     SCIP_VAR *y;
 *     union {
 *         SCIP_CONSNONLINEAR_AUXEXPR **exprs;
 *         SCIP_VAR *var;
 *     } aux;
 *     int nauxexprs;
 *     int auxexprssize;
 *     int nlockspos;
 *     int nlocksneg;
 *     unsigned int existing;
 * } SCIP_CONSNONLINEAR_BILINTERM
 * }
 */
public class SCIP_CONSNONLINEAR_BILINTERM$208 extends SCIP_ConsNonlinear_BilinTerm {

    SCIP_CONSNONLINEAR_BILINTERM$208() {
        // Should not be called directly
    }
}

