// Generated by jextract

package com.ustermetrics.scip4j.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct SCIP_AggrRow {
 *     double *vals;
 *     int *inds;
 *     int *rowsinds;
 *     int *slacksign;
 *     double *rowweights;
 *     double rhshi;
 *     double rhslo;
 *     int nnz;
 *     int nrows;
 *     int rowssize;
 *     int rank;
 *     unsigned int local;
 * } SCIP_AGGRROW
 * }
 */
public class SCIP_AGGRROW$202 extends SCIP_AggrRow {

    SCIP_AGGRROW$202() {
        // Should not be called directly
    }
}

