// Generated by jextract

package com.ustermetrics.scip4j.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct SCIP_NlpStatistics {
 *     int niterations;
 *     double totaltime;
 *     double evaltime;
 *     double consviol;
 *     double boundviol;
 * } SCIP_NLPSTATISTICS
 * }
 */
public class SCIP_NLPSTATISTICS$171 extends SCIP_NlpStatistics {

    SCIP_NLPSTATISTICS$171() {
        // Should not be called directly
    }
}

